import { createCategoryId, createGlobalToolId, createToolId, createAlternativeId } from '../src/lib/server/id';

export interface SeedData {
  categories: Array<{
    id: string;
    slug: string;
    name: string;
    emoji: string;
    description: string;
    isFeatured: boolean;
  }>;
  globalTools: Array<{
    id: string;
    slug: string;
    name: string;
    websiteUrl: string;
    logoUrl: string;
  }>;
  desiTools: Array<{
    id: string;
    slug: string;
    name: string;
    tagline: string;
    description: string;
    websiteUrl: string;
    logoUrl: string;
    primaryColor: string;
    categoryId: string;
    hasGstInvoice: boolean;
    hasIndianDataResidency: boolean;
    hasInrPricing: boolean;
    hasUpiSupport: boolean;
    isOpenSource: boolean;
    hasIstSupport: boolean;
    isSelfHostable: boolean;
    hasFreeTier: boolean;
    pricingModel: 'Free' | 'Freemium' | 'Paid' | 'Open-Source';
    startingPriceInr?: number;
    globalAlternatives: string[]; // Global tool slugs
  }>;
}

const catDev = createCategoryId();
const catObs = createCategoryId();
const catFin = createCategoryId();
const catCrm = createCategoryId();
const catProd = createCategoryId();
const catAi = createCategoryId();
const catSupport = createCategoryId();
const catHr = createCategoryId();

export const seedData: SeedData = {
  categories: [
    {
      id: catDev,
      slug: 'developer-tools',
      name: 'Developer Tools',
      emoji: '⚡',
      description: 'Internal tool builders, APIs, testing, and backend infrastructure.',
      isFeatured: true,
    },
    {
      id: catObs,
      slug: 'observability',
      name: 'Observability & APM',
      emoji: '📊',
      description: 'Metrics, logs, traces, and application monitoring platforms.',
      isFeatured: true,
    },
    {
      id: catFin,
      slug: 'billing-finance',
      name: 'Billing & Finance',
      emoji: '💳',
      description: 'Payment gateways, subscription billing, and GST accounting.',
      isFeatured: true,
    },
    {
      id: catCrm,
      slug: 'crm-sales',
      name: 'CRM & Marketing',
      emoji: '🎯',
      description: 'Customer relations, marketing automation, and lead capture.',
      isFeatured: true,
    },
    {
      id: catSupport,
      slug: 'customer-support',
      name: 'Customer Support',
      emoji: '💬',
      description: 'Helpdesk, ticketing, live chat, and AI customer agents.',
      isFeatured: true,
    },
    {
      id: catAi,
      slug: 'ai-machine-learning',
      name: 'AI & Machine Learning',
      emoji: '🧠',
      description: 'Indic voice synthesis, sovereign LLMs, and video generation.',
      isFeatured: true,
    },
    {
      id: catHr,
      slug: 'hr-payroll',
      name: 'HR & Payroll',
      emoji: '👥',
      description: 'Domestic compliance, payroll calculation, and attendance.',
      isFeatured: false,
    },
    {
      id: catProd,
      slug: 'productivity',
      name: 'Productivity & Docs',
      emoji: '✍️',
      description: 'Knowledge bases, collaboration, and documentation suites.',
      isFeatured: false,
    },
  ],

  globalTools: [
    {
      id: createGlobalToolId(),
      slug: 'datadog',
      name: 'Datadog',
      websiteUrl: 'https://datadoghq.com',
      logoUrl: 'https://logo.clearbit.com/datadoghq.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'retool',
      name: 'Retool',
      websiteUrl: 'https://retool.com',
      logoUrl: 'https://logo.clearbit.com/retool.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'stripe',
      name: 'Stripe',
      websiteUrl: 'https://stripe.com',
      logoUrl: 'https://logo.clearbit.com/stripe.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'salesforce',
      name: 'Salesforce',
      websiteUrl: 'https://salesforce.com',
      logoUrl: 'https://logo.clearbit.com/salesforce.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'zendesk',
      name: 'Zendesk',
      websiteUrl: 'https://zendesk.com',
      logoUrl: 'https://logo.clearbit.com/zendesk.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'saucelabs',
      name: 'Sauce Labs',
      websiteUrl: 'https://saucelabs.com',
      logoUrl: 'https://logo.clearbit.com/saucelabs.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'insomnia',
      name: 'Insomnia',
      websiteUrl: 'https://insomnia.rest',
      logoUrl: 'https://logo.clearbit.com/insomnia.rest',
    },
    {
      id: createGlobalToolId(),
      slug: 'gusto',
      name: 'Gusto',
      websiteUrl: 'https://gusto.com',
      logoUrl: 'https://logo.clearbit.com/gusto.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'elevenlabs',
      name: 'ElevenLabs',
      websiteUrl: 'https://elevenlabs.io',
      logoUrl: 'https://logo.clearbit.com/elevenlabs.io',
    },
    {
      id: createGlobalToolId(),
      slug: 'mixpanel',
      name: 'Mixpanel',
      websiteUrl: 'https://mixpanel.com',
      logoUrl: 'https://logo.clearbit.com/mixpanel.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'twilio',
      name: 'Twilio',
      websiteUrl: 'https://twilio.com',
      logoUrl: 'https://logo.clearbit.com/twilio.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'gitbook',
      name: 'GitBook',
      websiteUrl: 'https://gitbook.com',
      logoUrl: 'https://logo.clearbit.com/gitbook.com',
    },
    {
      id: createGlobalToolId(),
      slug: 'recurly',
      name: 'Recurly',
      websiteUrl: 'https://recurly.com',
      logoUrl: 'https://logo.clearbit.com/recurly.com',
    },
  ],

  desiTools: [
    {
      id: createToolId(),
      slug: 'signoz',
      name: 'SigNoz',
      tagline: 'Open-source APM, Tracing, Logs and Metrics built for scale',
      description: 'Single-pane observability platform based on OpenTelemetry and ClickHouse. Native INR pricing, self-hostable, and zero USD egress surcharges.',
      websiteUrl: 'https://signoz.io',
      logoUrl: 'https://signoz.io/img/signoz-logo.svg',
      primaryColor: '#EE6C4D',
      categoryId: catObs,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: true,
      hasIstSupport: true,
      isSelfHostable: true,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 0,
      globalAlternatives: ['datadog'],
    },
    {
      id: createToolId(),
      slug: 'appsmith',
      name: 'Appsmith',
      tagline: 'Build internal tools, admin panels, and dashboards in minutes',
      description: 'Open-source low-code internal tool framework with native database integrations, custom JS scripts, and Indian cloud hosting options.',
      websiteUrl: 'https://appsmith.com',
      logoUrl: 'https://assets.appsmith.com/appsmith-logo.svg',
      primaryColor: '#F36A4A',
      categoryId: catDev,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: true,
      hasIstSupport: true,
      isSelfHostable: true,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 0,
      globalAlternatives: ['retool'],
    },
    {
      id: createToolId(),
      slug: 'postman',
      name: 'Postman',
      tagline: 'The complete API platform for building, testing, and designing APIs',
      description: 'Founded in Bengaluru, Postman is the world-leading API collaborative environment with workspace synchronization and mock servers.',
      websiteUrl: 'https://postman.com',
      logoUrl: 'https://assets.getpostman.com/common-share/postman-logo-stacked.svg',
      primaryColor: '#FF6C37',
      categoryId: catDev,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 1200,
      globalAlternatives: ['insomnia'],
    },
    {
      id: createToolId(),
      slug: 'browserstack',
      name: 'BrowserStack',
      tagline: 'Instant cross-browser and mobile device testing platform in the cloud',
      description: 'Test websites and mobile apps across 3,000+ real browsers and devices with high speed, zero maintenance, and local Indian billing.',
      websiteUrl: 'https://browserstack.com',
      logoUrl: 'https://static.browserstack.com/images/browserstack-logo-600x600.png',
      primaryColor: '#0052CC',
      categoryId: catDev,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Paid',
      startingPriceInr: 2400,
      globalAlternatives: ['saucelabs'],
    },
    {
      id: createToolId(),
      slug: 'chargebee',
      name: 'Chargebee',
      tagline: 'Subscription management and recurring billing infrastructure',
      description: 'Manage complex recurring SaaS subscriptions, automated dunning, GST invoices, and global tax compliance originating from Chennai.',
      websiteUrl: 'https://chargebee.com',
      logoUrl: 'https://webstatic.chargebee.com/assets/web/600/images/footer/chargebee-logo-black.svg',
      primaryColor: '#6C5CE7',
      categoryId: catFin,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 0,
      globalAlternatives: ['recurly', 'stripe'],
    },
    {
      id: createToolId(),
      slug: 'razorpay',
      name: 'Razorpay',
      tagline: 'Payments, banking, and financial suite for Indian internet businesses',
      description: 'Accept UPI, Cards, Netbanking, EMI, and Wallets with 99.9% uptime, instant settlements, and comprehensive GST reconciliation.',
      websiteUrl: 'https://razorpay.com',
      logoUrl: 'https://razorpay.com/assets/razorpay-glyph.svg',
      primaryColor: '#0C2340',
      categoryId: catFin,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Free',
      startingPriceInr: 0,
      globalAlternatives: ['stripe'],
    },
    {
      id: createToolId(),
      slug: 'freshdesk',
      name: 'Freshdesk',
      tagline: 'Omnichannel customer support software powered by Freddy AI',
      description: 'Unified ticketing, live chat, telephony, and self-service knowledge base built by Freshworks in Chennai with local INR billing.',
      websiteUrl: 'https://freshdesk.com',
      logoUrl: 'https://assets.freshdesk.com/skin/freshdesk-logo.svg',
      primaryColor: '#00A88F',
      categoryId: catSupport,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 999,
      globalAlternatives: ['zendesk'],
    },
    {
      id: createToolId(),
      slug: 'zoho-crm',
      name: 'Zoho CRM',
      tagline: 'Supercharge your sales team with 360-degree customer relationship management',
      description: 'Pioneering sovereign CRM software suite with automated lead routing, Zia AI sales assistant, domestic data residency, and GST compliance.',
      websiteUrl: 'https://zoho.com/crm',
      logoUrl: 'https://www.zohowebstatic.com/sites/zweb/images/common/zoho-logo-web.svg',
      primaryColor: '#ED1C24',
      categoryId: catCrm,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 800,
      globalAlternatives: ['salesforce'],
    },
    {
      id: createToolId(),
      slug: 'murf-ai',
      name: 'Murf AI',
      tagline: 'Studio-quality realistic AI voiceovers and text-to-speech engine',
      description: 'Generate hyper-realistic synthetic voices in multiple Indian accents and international languages for videos, podcasts, and e-learning.',
      websiteUrl: 'https://murf.ai',
      logoUrl: 'https://murf.ai/static/media/logo.3c6e9ec1.svg',
      primaryColor: '#6366F1',
      categoryId: catAi,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 1500,
      globalAlternatives: ['elevenlabs'],
    },
    {
      id: createToolId(),
      slug: 'clevertap',
      name: 'CleverTap',
      tagline: 'All-in-one customer engagement and retention platform for mobile apps',
      description: 'Real-time user behavioral analytics, predictive segmentation, omnichannel push notifications, and lifecycle automation.',
      websiteUrl: 'https://clevertap.com',
      logoUrl: 'https://clevertap.com/wp-content/themes/clevertap/assets/images/logo.svg',
      primaryColor: '#D81B60',
      categoryId: catCrm,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: false,
      pricingModel: 'Paid',
      startingPriceInr: 5000,
      globalAlternatives: ['mixpanel'],
    },
    {
      id: createToolId(),
      slug: 'keka',
      name: 'Keka HR',
      tagline: 'Modern HR, Payroll, Leave, and Performance Management for Indian teams',
      description: 'Automated statutory PF, ESI, TDS, PT tax calculations, geofenced attendance, and employee self-service portal.',
      websiteUrl: 'https://keka.com',
      logoUrl: 'https://cdn.keka.com/brand/keka-logo-blue.svg',
      primaryColor: '#2563EB',
      categoryId: catHr,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: false,
      pricingModel: 'Paid',
      startingPriceInr: 6999,
      globalAlternatives: ['gusto'],
    },
    {
      id: createToolId(),
      slug: 'document360',
      name: 'Document360',
      tagline: 'Knowledge base platform for technical documentation and SOPs',
      description: 'Create private and public knowledge bases, product documentation, and API guides with markdown editor and version control.',
      websiteUrl: 'https://document360.com',
      logoUrl: 'https://document360.com/wp-content/themes/document360/images/document360-logo.svg',
      primaryColor: '#4F46E5',
      categoryId: catProd,
      hasGstInvoice: true,
      hasIndianDataResidency: true,
      hasInrPricing: true,
      hasUpiSupport: true,
      isOpenSource: false,
      hasIstSupport: true,
      isSelfHostable: false,
      hasFreeTier: true,
      pricingModel: 'Freemium',
      startingPriceInr: 3000,
      globalAlternatives: ['gitbook'],
    },
  ],
};
