UPDATE categories SET description = 'Powerful AI and machine learning models built for the Indian context, from vernacular LLMs to enterprise automation.' WHERE slug = 'ai-machine-learning';
UPDATE categories SET description = 'GST-ready billing and finance software to automate invoicing, manage subscriptions, and claim input tax credits effortlessly.' WHERE slug = 'billing-finance';
UPDATE categories SET description = 'High-performance brokerage platforms and APIs for seamless stock trading and wealth management in the Indian market.' WHERE slug = 'brokerage';
UPDATE categories SET description = 'Privacy-first web browsers built in India for secure, fast, and deeply localized internet experiences.' WHERE slug = 'browser';
UPDATE categories SET description = 'High-conversion CRM and sales software built to close deals, manage pipelines, and scale Indian revenue teams.' WHERE slug = 'crm-sales';
UPDATE categories SET description = 'Secure crypto exchanges and portfolio trackers optimized for India’s unique regulatory and tax landscape.' WHERE slug = 'crypto';
UPDATE categories SET description = 'Omnichannel helpdesk and support tools designed for high-velocity teams, backed by IST-aligned engineering.' WHERE slug = 'customer-support';
UPDATE categories SET description = 'Scalable databases and cloud infrastructure keeping your sensitive records safely within Indian DPDP jurisdiction.' WHERE slug = 'database';
UPDATE categories SET description = 'World-class developer tools, testing frameworks, and APIs engineered by Indian builders for global scale.' WHERE slug = 'developer-tools';
UPDATE categories SET description = 'Reliable email hosting and marketing platforms delivering high inbox placement and secure domestic data residency.' WHERE slug = 'email';
UPDATE categories SET description = 'Automated HRMS and payroll software that actually understands Indian tax slabs, PF, and local compliance laws.' WHERE slug = 'hr-payroll';
UPDATE categories SET description = 'Secure, homegrown messenger apps for encrypted team collaboration and seamless personal communication.' WHERE slug = 'messenger';
UPDATE categories SET description = 'Insightful Indian media stacks and newsletters covering local business, deep tech, and the sovereign startup ecosystem.' WHERE slug = 'newsletter';
UPDATE categories SET description = 'Unified APM and observability platforms to monitor uptime and troubleshoot infrastructure without the massive USD markup.' WHERE slug = 'observability';
UPDATE categories SET description = 'Collaborative office suites and document editors for Indian teams to create, share, and store work on sovereign servers.' WHERE slug = 'office-suite';
UPDATE categories SET description = 'Next-generation payment gateways and UPI infrastructure powering frictionless direct INR checkouts and high success rates.' WHERE slug = 'payments';
UPDATE categories SET description = 'Intuitive productivity and project management hubs to keep your startup organized and relentlessly focused on execution.' WHERE slug = 'productivity';
UPDATE categories SET description = 'Enterprise-grade workplace chat and video conferencing tools designed to replace global giants without compromising speed.' WHERE slug = 'team-communication';
UPDATE categories SET description = 'High-speed, encrypted virtual private networks ensuring secure internet access and enterprise data protection across India.' WHERE slug = 'vpn';
